---
language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install autoconf
  - sudo apt-get -y install automake
  - sudo apt-get -y install libtool
  - sudo apt-get -y install libusb-dev
  - sudo apt-get -y install libusb-1.0
  - sudo apt-get -y install libglib2.0-dev
  - sudo apt-get -y install pkg-config

script:
  - autoreconf -fis
  - autoconf
  - aclocal
  - automake --add-missing --foreign
  - ./configure
  - make -j
  - src/tiva-dfu-prog
  - if [ $? -eq 1 ] ; then exit 0; fi

notifications:
  email: false