---
language: cpp
compiler: gcc
sudo: required
dist: bionic

install:
  - autoconf
  - automake
  - curl
  - libtool
  - libusb-dev
  - libusb-1.0
  - libglib2.0-dev
  - pkg-config

script:
  - autoreconf -fis
  - autoconf
  - aclocal
  - automake --add-missing --foreign
  - ./configure
  - make -j
  - src/tiva-dfu-prog

notifications:
  email: false